@startuml

title WhackAMole活动图

start

:启动应用;

:显示游戏主界面;

repeat :开始游戏循环;
  if (是否查看历史记录?) then (是)
    :切换到历史记录界面;
    :显示历史得分列表;
    :点击返回游戏;
  else (否)
  endif
  
  :显示游戏主界面;
  
  if (游戏是否已开始?) then (否)
    :点击"开始游戏"按钮;
    :初始化游戏状态;
    :启动游戏计时器;
  else (是)
  endif
  
  while (游戏时间 > 0?) is (是)
    :随机更新地鼠位置;
    if (用户点击屏幕?) then (是)
      if (击中地鼠?) then (是)
        :播放击中音效;
        :增加分数;
      else (否)
        :播放击空音效;
        :减少分数;
      endif
    else (否)
    endif
    :更新显示;
    :等待一秒;
  endwhile (否)
  
  :结束游戏;
  :保存分数;
  :显示游戏结束对话框;
  
  if (用户选择重新开始?) then (是)
    :重置游戏状态;
  else (否)
  endif
  
repeat while (用户继续玩游戏?) is (是)

stop

@enduml 